/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteSiteIdRouteImport } from './routes/site/$siteId'
import { Route as SiteSiteIdIndexRouteImport } from './routes/site/$siteId/index'
import { Route as SiteSiteIdCodeRouteImport } from './routes/site/$siteId/code'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSiteIdRoute = SiteSiteIdRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSiteIdIndexRoute = SiteSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteSiteIdRoute,
} as any)
const SiteSiteIdCodeRoute = SiteSiteIdCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => SiteSiteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/site/$siteId': typeof SiteSiteIdRouteWithChildren
  '/site/$siteId/code': typeof SiteSiteIdCodeRoute
  '/site/$siteId/': typeof SiteSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/site/$siteId/code': typeof SiteSiteIdCodeRoute
  '/site/$siteId': typeof SiteSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/site/$siteId': typeof SiteSiteIdRouteWithChildren
  '/site/$siteId/code': typeof SiteSiteIdCodeRoute
  '/site/$siteId/': typeof SiteSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/site/$siteId'
    | '/site/$siteId/code'
    | '/site/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding' | '/site/$siteId/code' | '/site/$siteId'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/site/$siteId'
    | '/site/$siteId/code'
    | '/site/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  SiteSiteIdRoute: typeof SiteSiteIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$siteId': {
      id: '/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof SiteSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$siteId/': {
      id: '/site/$siteId/'
      path: '/'
      fullPath: '/site/$siteId/'
      preLoaderRoute: typeof SiteSiteIdIndexRouteImport
      parentRoute: typeof SiteSiteIdRoute
    }
    '/site/$siteId/code': {
      id: '/site/$siteId/code'
      path: '/code'
      fullPath: '/site/$siteId/code'
      preLoaderRoute: typeof SiteSiteIdCodeRouteImport
      parentRoute: typeof SiteSiteIdRoute
    }
  }
}

interface SiteSiteIdRouteChildren {
  SiteSiteIdCodeRoute: typeof SiteSiteIdCodeRoute
  SiteSiteIdIndexRoute: typeof SiteSiteIdIndexRoute
}

const SiteSiteIdRouteChildren: SiteSiteIdRouteChildren = {
  SiteSiteIdCodeRoute: SiteSiteIdCodeRoute,
  SiteSiteIdIndexRoute: SiteSiteIdIndexRoute,
}

const SiteSiteIdRouteWithChildren = SiteSiteIdRoute._addFileChildren(
  SiteSiteIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  SiteSiteIdRoute: SiteSiteIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
