/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteSiteIdRouteImport } from './routes/site/$siteId'
import { Route as SiteSiteIdIndexRouteImport } from './routes/site/$siteId/index'
import { Route as SiteSiteIdWoocommerceRouteImport } from './routes/site/$siteId/woocommerce'
import { Route as SiteSiteIdSystemRouteImport } from './routes/site/$siteId/system'
import { Route as SiteSiteIdAnalyticsRouteImport } from './routes/site/$siteId/analytics'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSiteIdRoute = SiteSiteIdRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSiteIdIndexRoute = SiteSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteSiteIdRoute,
} as any)
const SiteSiteIdWoocommerceRoute = SiteSiteIdWoocommerceRouteImport.update({
  id: '/woocommerce',
  path: '/woocommerce',
  getParentRoute: () => SiteSiteIdRoute,
} as any)
const SiteSiteIdSystemRoute = SiteSiteIdSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => SiteSiteIdRoute,
} as any)
const SiteSiteIdAnalyticsRoute = SiteSiteIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SiteSiteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/site/$siteId': typeof SiteSiteIdRouteWithChildren
  '/site/$siteId/analytics': typeof SiteSiteIdAnalyticsRoute
  '/site/$siteId/system': typeof SiteSiteIdSystemRoute
  '/site/$siteId/woocommerce': typeof SiteSiteIdWoocommerceRoute
  '/site/$siteId/': typeof SiteSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/site/$siteId/analytics': typeof SiteSiteIdAnalyticsRoute
  '/site/$siteId/system': typeof SiteSiteIdSystemRoute
  '/site/$siteId/woocommerce': typeof SiteSiteIdWoocommerceRoute
  '/site/$siteId': typeof SiteSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/site/$siteId': typeof SiteSiteIdRouteWithChildren
  '/site/$siteId/analytics': typeof SiteSiteIdAnalyticsRoute
  '/site/$siteId/system': typeof SiteSiteIdSystemRoute
  '/site/$siteId/woocommerce': typeof SiteSiteIdWoocommerceRoute
  '/site/$siteId/': typeof SiteSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/onboarding'
    | '/settings'
    | '/site/$siteId'
    | '/site/$siteId/analytics'
    | '/site/$siteId/system'
    | '/site/$siteId/woocommerce'
    | '/site/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/onboarding'
    | '/settings'
    | '/site/$siteId/analytics'
    | '/site/$siteId/system'
    | '/site/$siteId/woocommerce'
    | '/site/$siteId'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/onboarding'
    | '/settings'
    | '/site/$siteId'
    | '/site/$siteId/analytics'
    | '/site/$siteId/system'
    | '/site/$siteId/woocommerce'
    | '/site/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  SiteSiteIdRoute: typeof SiteSiteIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$siteId': {
      id: '/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof SiteSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$siteId/': {
      id: '/site/$siteId/'
      path: '/'
      fullPath: '/site/$siteId/'
      preLoaderRoute: typeof SiteSiteIdIndexRouteImport
      parentRoute: typeof SiteSiteIdRoute
    }
    '/site/$siteId/woocommerce': {
      id: '/site/$siteId/woocommerce'
      path: '/woocommerce'
      fullPath: '/site/$siteId/woocommerce'
      preLoaderRoute: typeof SiteSiteIdWoocommerceRouteImport
      parentRoute: typeof SiteSiteIdRoute
    }
    '/site/$siteId/system': {
      id: '/site/$siteId/system'
      path: '/system'
      fullPath: '/site/$siteId/system'
      preLoaderRoute: typeof SiteSiteIdSystemRouteImport
      parentRoute: typeof SiteSiteIdRoute
    }
    '/site/$siteId/analytics': {
      id: '/site/$siteId/analytics'
      path: '/analytics'
      fullPath: '/site/$siteId/analytics'
      preLoaderRoute: typeof SiteSiteIdAnalyticsRouteImport
      parentRoute: typeof SiteSiteIdRoute
    }
  }
}

interface SiteSiteIdRouteChildren {
  SiteSiteIdAnalyticsRoute: typeof SiteSiteIdAnalyticsRoute
  SiteSiteIdSystemRoute: typeof SiteSiteIdSystemRoute
  SiteSiteIdWoocommerceRoute: typeof SiteSiteIdWoocommerceRoute
  SiteSiteIdIndexRoute: typeof SiteSiteIdIndexRoute
}

const SiteSiteIdRouteChildren: SiteSiteIdRouteChildren = {
  SiteSiteIdAnalyticsRoute: SiteSiteIdAnalyticsRoute,
  SiteSiteIdSystemRoute: SiteSiteIdSystemRoute,
  SiteSiteIdWoocommerceRoute: SiteSiteIdWoocommerceRoute,
  SiteSiteIdIndexRoute: SiteSiteIdIndexRoute,
}

const SiteSiteIdRouteWithChildren = SiteSiteIdRoute._addFileChildren(
  SiteSiteIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  SiteSiteIdRoute: SiteSiteIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
